package br.com.champtech;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Fukutu
 */
public class EsseAqui extends javax.swing.JFrame {

    private CardLayout cardLayout;

    /**
     * Creates new form Teste
     */
    public EsseAqui() {
        initComponents();

        this.cardLayout = (CardLayout) this.contentPanel.getLayout();

        ImageIcon logoIcon = new ImageIcon("ïmages/logo.png");
        //logoIcon.setImage(logoIcon.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH));
        //logo.setIcon(logoIcon);

    }

    /**
     * This method is called from within the constructor to initialize the
     * form.í WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        windowBarPanel = new javax.swing.JPanel();
        windowCloseButton = new javax.swing.JButton();
        windowMinimizeButton = new javax.swing.JButton();
        windowContent = new javax.swing.JPanel();
        menuBarPanel = new javax.swing.JPanel();
        avisosButton = new javax.swing.JButton();
        produtosButton = new javax.swing.JButton();
        funcionariosButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();
        histButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        avisosPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        produtosPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        funcionariosPanel = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        configPanel = new javax.swing.JPanel();
        historicoPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(204, 0, 153));
        mainPanel.setFocusable(false);
        mainPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setRequestFocusEnabled(false);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowBarPanel.setBackground(new java.awt.Color(0, 0, 0));
        windowBarPanel.setMinimumSize(new java.awt.Dimension(800, 22));
        windowBarPanel.setPreferredSize(new java.awt.Dimension(800, 22));
        windowBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowCloseButton.setBackground(new java.awt.Color(204, 51, 0));
        windowCloseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        windowCloseButton.setForeground(new java.awt.Color(255, 255, 255));
        windowCloseButton.setText("X");
        windowCloseButton.setBorder(null);
        windowCloseButton.setBorderPainted(false);
        windowCloseButton.setFocusPainted(false);
        windowCloseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        windowCloseButton.setPreferredSize(new java.awt.Dimension(15, 13));
        windowCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowCloseButtonActionPerformed(evt);
            }
        });
        windowBarPanel.add(windowCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 5, -1, -1));

        windowMinimizeButton.setBackground(new java.awt.Color(255, 153, 0));
        windowMinimizeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        windowMinimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        windowMinimizeButton.setText("-");
        windowMinimizeButton.setBorder(null);
        windowMinimizeButton.setBorderPainted(false);
        windowMinimizeButton.setFocusPainted(false);
        windowMinimizeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        windowMinimizeButton.setPreferredSize(new java.awt.Dimension(15, 13));
        windowMinimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowMinimizeButtonActionPerformed(evt);
            }
        });
        windowBarPanel.add(windowMinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 5, -1, -1));

        mainPanel.add(windowBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        windowContent.setBackground(new java.awt.Color(255, 255, 255));
        windowContent.setMaximumSize(new java.awt.Dimension(800, 458));
        windowContent.setMinimumSize(new java.awt.Dimension(800, 458));
        windowContent.setPreferredSize(new java.awt.Dimension(800, 578));
        windowContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBarPanel.setBackground(new java.awt.Color(51, 51, 51));
        menuBarPanel.setPreferredSize(new java.awt.Dimension(180, 578));
        menuBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avisosButton.setBackground(new java.awt.Color(51, 51, 51));
        avisosButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        avisosButton.setForeground(new java.awt.Color(255, 255, 255));
        avisosButton.setText("Avisos");
        avisosButton.setBorder(null);
        avisosButton.setContentAreaFilled(false);
        avisosButton.setFocusPainted(false);
        avisosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avisosButtonActionPerformed(evt);
            }
        });
        menuBarPanel.add(avisosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 40));

        produtosButton.setBackground(new java.awt.Color(51, 51, 51));
        produtosButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        produtosButton.setForeground(new java.awt.Color(255, 255, 255));
        produtosButton.setText("Produtos");
        produtosButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(102, 102, 102)));
        produtosButton.setContentAreaFilled(false);
        produtosButton.setFocusPainted(false);
        produtosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                produtosButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                produtosButtonMouseExited(evt);
            }
        });
        produtosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosButtonActionPerformed(evt);
            }
        });
        menuBarPanel.add(produtosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        funcionariosButton.setBackground(new java.awt.Color(51, 51, 51));
        funcionariosButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        funcionariosButton.setForeground(new java.awt.Color(255, 255, 255));
        funcionariosButton.setText("Funcionários");
        funcionariosButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(102, 102, 102)));
        funcionariosButton.setContentAreaFilled(false);
        funcionariosButton.setFocusPainted(false);
        funcionariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosButtonActionPerformed(evt);
            }
        });
        menuBarPanel.add(funcionariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 40));

        configButton.setBackground(new java.awt.Color(51, 51, 51));
        configButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        configButton.setForeground(new java.awt.Color(255, 255, 255));
        configButton.setText("Configurações");
        configButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(102, 102, 102)));
        configButton.setContentAreaFilled(false);
        configButton.setFocusPainted(false);
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });
        menuBarPanel.add(configButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 40));

        histButton.setBackground(new java.awt.Color(51, 51, 51));
        histButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        histButton.setForeground(new java.awt.Color(255, 255, 255));
        histButton.setText("Historico");
        histButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(102, 102, 102)));
        histButton.setContentAreaFilled(false);
        histButton.setFocusPainted(false);
        histButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histButtonActionPerformed(evt);
            }
        });
        menuBarPanel.add(histButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 40));

        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 40));
        menuBarPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pedro almeida");
        menuBarPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 100, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administrador");
        menuBarPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 535, 100, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(9, 9));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuBarPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 560, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton2.setFocusPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(9, 9));
        menuBarPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 539, 20, 20));

        windowContent.add(menuBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setPreferredSize(new java.awt.Dimension(610, 578));
        contentPanel.setLayout(new java.awt.CardLayout());

        avisosPanel.setBackground(new java.awt.Color(255, 255, 255));
        avisosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setOpaque(false);
        jScrollPane7.setPreferredSize(new java.awt.Dimension(454, 600));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Denis Stiehler", "31/10/2019 19:58", "Churrasco na casa do Nathan amanhã ---------------------------------------------------------------------------"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Autor", "Data", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable7.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable7.setGridColor(new java.awt.Color(51, 51, 51));
        jTable7.setName("Tabela de Avisos"); // NOI18N
        jTable7.setOpaque(false);
        jTable7.setPreferredSize(new java.awt.Dimension(610, 250));
        jTable7.setRowHeight(50);
        jScrollPane7.setViewportView(jTable7);
        jTable7.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(0).setResizable(false);
            jTable7.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTable7.getColumnModel().getColumn(1).setResizable(false);
            jTable7.getColumnModel().getColumn(1).setPreferredWidth(110);
            jTable7.getColumnModel().getColumn(2).setResizable(false);
            jTable7.getColumnModel().getColumn(2).setPreferredWidth(490);
        }

        avisosPanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 610, 528));

        contentPanel.add(avisosPanel, "avisosCard");

        produtosPanel.setBackground(new java.awt.Color(255, 255, 255));
        produtosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setOpaque(false);
        jScrollPane8.setPreferredSize(new java.awt.Dimension(454, 600));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Denis Stiehler", "31/10/2019 19:58", "Churrasco na casa do Nathan amanhã ---------------------------------------------------------------------------"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Autor", "Data", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable8.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable8.setGridColor(new java.awt.Color(51, 51, 51));
        jTable8.setName("Tabela de Avisos"); // NOI18N
        jTable8.setOpaque(false);
        jTable8.setPreferredSize(new java.awt.Dimension(610, 250));
        jTable8.setRowHeight(50);
        jScrollPane8.setViewportView(jTable8);
        jTable8.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable8.getColumnModel().getColumnCount() > 0) {
            jTable8.getColumnModel().getColumn(0).setResizable(false);
            jTable8.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTable8.getColumnModel().getColumn(1).setResizable(false);
            jTable8.getColumnModel().getColumn(1).setPreferredWidth(110);
            jTable8.getColumnModel().getColumn(2).setResizable(false);
            jTable8.getColumnModel().getColumn(2).setPreferredWidth(490);
        }

        produtosPanel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 610, 528));

        contentPanel.add(produtosPanel, "produtosCard");

        funcionariosPanel.setBackground(new java.awt.Color(255, 255, 255));
        funcionariosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane9.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setOpaque(false);
        jScrollPane9.setPreferredSize(new java.awt.Dimension(454, 600));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Denis Stiehler", "31/10/2019 19:58", "Churrasco na casa do Nathan amanhã ---------------------------------------------------------------------------"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Autor", "Data", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable9.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable9.setGridColor(new java.awt.Color(51, 51, 51));
        jTable9.setName("Tabela de Avisos"); // NOI18N
        jTable9.setOpaque(false);
        jTable9.setPreferredSize(new java.awt.Dimension(610, 250));
        jTable9.setRowHeight(50);
        jScrollPane9.setViewportView(jTable9);
        jTable9.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable9.getColumnModel().getColumnCount() > 0) {
            jTable9.getColumnModel().getColumn(0).setResizable(false);
            jTable9.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTable9.getColumnModel().getColumn(1).setResizable(false);
            jTable9.getColumnModel().getColumn(1).setPreferredWidth(110);
            jTable9.getColumnModel().getColumn(2).setResizable(false);
            jTable9.getColumnModel().getColumn(2).setPreferredWidth(490);
        }

        funcionariosPanel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, 610, 200));

        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        funcionariosPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        jScrollPane2.setViewportView(jEditorPane1);

        funcionariosPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 300, 70));

        contentPanel.add(funcionariosPanel, "funcionariosCard");

        configPanel.setBackground(new java.awt.Color(255, 255, 255));
        configPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contentPanel.add(configPanel, "configCard");

        historicoPanel.setBackground(new java.awt.Color(255, 255, 255));
        historicoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setOpaque(false);
        jScrollPane6.setPreferredSize(new java.awt.Dimension(454, 600));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Denis Stiehler", "31/10/2019 19:58", "Churrasco na casa do Nathan amanhã ---------------------------------------------------------------------------"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Autor", "Data", "Mensagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable6.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable6.setGridColor(new java.awt.Color(51, 51, 51));
        jTable6.setName("Tabela de Avisos"); // NOI18N
        jTable6.setOpaque(false);
        jTable6.setPreferredSize(new java.awt.Dimension(610, 250));
        jTable6.setRowHeight(50);
        jScrollPane6.setViewportView(jTable6);
        jTable6.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(0).setResizable(false);
            jTable6.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTable6.getColumnModel().getColumn(1).setResizable(false);
            jTable6.getColumnModel().getColumn(1).setPreferredWidth(110);
            jTable6.getColumnModel().getColumn(2).setResizable(false);
            jTable6.getColumnModel().getColumn(2).setPreferredWidth(490);
        }

        historicoPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 610, 528));

        contentPanel.add(historicoPanel, "historicoCard");

        windowContent.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        mainPanel.add(windowContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void windowMinimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowMinimizeButtonActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_windowMinimizeButtonActionPerformed

    private void windowCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowCloseButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_windowCloseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void avisosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avisosButtonActionPerformed
        this.cardLayout.show(contentPanel, "avisosCard");
    }//GEN-LAST:event_avisosButtonActionPerformed

    private void produtosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosButtonActionPerformed
        this.cardLayout.show(contentPanel, "produtosCard");
    }//GEN-LAST:event_produtosButtonActionPerformed

    private void funcionariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosButtonActionPerformed
        this.cardLayout.show(contentPanel, "funcionariosCard");
    }//GEN-LAST:event_funcionariosButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        this.cardLayout.show(contentPanel, "configCard");
    }//GEN-LAST:event_configButtonActionPerformed

    private void histButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histButtonActionPerformed
        this.cardLayout.show(contentPanel, "historicoCard");
    }//GEN-LAST:event_histButtonActionPerformed

    private void produtosButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_produtosButtonMouseEntered

    private void produtosButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_produtosButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsseAqui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avisosButton;
    private javax.swing.JPanel avisosPanel;
    private javax.swing.JButton configButton;
    private javax.swing.JPanel configPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton funcionariosButton;
    private javax.swing.JPanel funcionariosPanel;
    private javax.swing.JButton histButton;
    private javax.swing.JPanel historicoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuBarPanel;
    private javax.swing.JButton produtosButton;
    private javax.swing.JPanel produtosPanel;
    private javax.swing.JPanel windowBarPanel;
    private javax.swing.JButton windowCloseButton;
    private javax.swing.JPanel windowContent;
    private javax.swing.JButton windowMinimizeButton;
    // End of variables declaration//GEN-END:variables
}
