package br.com.champtech;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Fukutu
 */
public class Teste_1 extends javax.swing.JFrame {

    private CardLayout cardLayout;
    
    /**
     * Creates new form Teste
     */
    public Teste_1() {
        initComponents();
        this.cardLayout = (CardLayout) this.contentPanel.getLayout();
        
        ImageIcon logo = new ImageIcon("images/logo.png");
        logo.setImage(logo.getImage().getScaledInstance(logoLabel.getWidth(), logoLabel.getHeight(), Image.SCALE_SMOOTH));
        logoLabel.setIcon(logo);
        
        ImageIcon lupa = new ImageIcon("images/lupa.png");
        lupa.setImage(lupa.getImage().getScaledInstance(buscarLabel.getWidth(), buscarLabel.getHeight(), Image.SCALE_SMOOTH));
        buscarLabel.setIcon(lupa);
        
        ImageIcon user = new ImageIcon("images/user.png");
        user.setImage(user.getImage().getScaledInstance(userButton.getWidth(), userButton.getHeight(), Image.SCALE_SMOOTH));
        userButton.setIcon(user);
        
        ImageIcon dropdown = new ImageIcon("images/dropdown.png");
        dropdown.setImage(dropdown.getImage().getScaledInstance(departamentosButton.getWidth(), departamentosButton.getHeight(), Image.SCALE_SMOOTH));
        departamentosButton.setIcon(dropdown);
    
        ImageIcon carroIcon = new ImageIcon("images/9.jpg");
        carroIcon.setImage(carroIcon.getImage().getScaledInstance(carro.getWidth(), carro.getHeight(), Image.SCALE_SMOOTH));
        carro.setIcon(carroIcon);
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        windowBarPanel = new javax.swing.JPanel();
        windowCloseButton = new javax.swing.JButton();
        windowMinimizeButton = new javax.swing.JButton();
        menuBarPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        buscarLabel = new javax.swing.JLabel();
        departamentosButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        produtosScrollPane = new javax.swing.JScrollPane();
        produtosPanel = new javax.swing.JPanel();
        carro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        montagemScrollPane = new javax.swing.JScrollPane();
        montagemPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        homeScrollPane = new javax.swing.JScrollPane();
        homePanel = new javax.swing.JPanel();
        loginScrollPane = new javax.swing.JScrollPane();
        loginPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(204, 0, 153));
        mainPanel.setFocusable(false);
        mainPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setRequestFocusEnabled(false);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowBarPanel.setBackground(new java.awt.Color(0, 0, 0));
        windowBarPanel.setMinimumSize(new java.awt.Dimension(800, 22));
        windowBarPanel.setPreferredSize(new java.awt.Dimension(800, 22));
        windowBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowCloseButton.setBackground(new java.awt.Color(204, 51, 0));
        windowCloseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        windowCloseButton.setForeground(new java.awt.Color(255, 255, 255));
        windowCloseButton.setText("X");
        windowCloseButton.setBorder(null);
        windowCloseButton.setBorderPainted(false);
        windowCloseButton.setFocusPainted(false);
        windowCloseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        windowCloseButton.setPreferredSize(new java.awt.Dimension(15, 13));
        windowCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                windowCloseButtonMouseClicked(evt);
            }
        });
        windowBarPanel.add(windowCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 5, -1, -1));

        windowMinimizeButton.setBackground(new java.awt.Color(255, 153, 0));
        windowMinimizeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        windowMinimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        windowMinimizeButton.setText("-");
        windowMinimizeButton.setBorder(null);
        windowMinimizeButton.setBorderPainted(false);
        windowMinimizeButton.setFocusPainted(false);
        windowMinimizeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        windowMinimizeButton.setPreferredSize(new java.awt.Dimension(15, 13));
        windowMinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                windowMinimizeButtonMouseClicked(evt);
            }
        });
        windowMinimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowMinimizeButtonActionPerformed(evt);
            }
        });
        windowBarPanel.add(windowMinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 5, -1, -1));

        mainPanel.add(windowBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuBarPanel.setBackground(new java.awt.Color(51, 51, 51));
        menuBarPanel.setMinimumSize(new java.awt.Dimension(800, 80));
        menuBarPanel.setPreferredSize(new java.awt.Dimension(800, 80));
        menuBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setOpaque(false);
        menuBarPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 240, 30));

        logoLabel.setBackground(new java.awt.Color(255, 255, 255));
        menuBarPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 200, 40));

        buscarLabel.setBackground(new java.awt.Color(255, 255, 255));
        menuBarPanel.add(buscarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 30, 30));

        departamentosButton.setBackground(new java.awt.Color(255, 255, 255));
        departamentosButton.setForeground(new java.awt.Color(255, 255, 255));
        departamentosButton.setBorderPainted(false);
        departamentosButton.setFocusPainted(false);
        departamentosButton.setOpaque(false);
        menuBarPanel.add(departamentosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, 30, 30));

        userButton.setBackground(new java.awt.Color(255, 255, 255));
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.setFocusPainted(false);
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        menuBarPanel.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 40, 40));

        mainPanel.add(menuBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, -1));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(800, 458));
        contentPanel.setMinimumSize(new java.awt.Dimension(800, 458));
        contentPanel.setPreferredSize(new java.awt.Dimension(800, 498));
        contentPanel.setLayout(new java.awt.CardLayout());

        produtosScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        produtosScrollPane.setBorder(null);
        produtosScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        produtosPanel.setBackground(new java.awt.Color(0, 0, 0));
        produtosPanel.setMaximumSize(new java.awt.Dimension(800, 32767));
        produtosPanel.setMinimumSize(new java.awt.Dimension(800, 458));
        produtosPanel.setPreferredSize(new java.awt.Dimension(800, 1000));
        produtosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produtosPanel.add(carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 290));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        produtosPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        produtosScrollPane.setViewportView(produtosPanel);

        contentPanel.add(produtosScrollPane, "produtosCard");

        montagemScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        montagemScrollPane.setBorder(null);
        montagemScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        montagemScrollPane.setMaximumSize(new java.awt.Dimension(800, 32767));
        montagemScrollPane.setMinimumSize(new java.awt.Dimension(800, 458));

        montagemPanel.setBackground(new java.awt.Color(255, 255, 255));
        montagemPanel.setMaximumSize(new java.awt.Dimension(800, 32767));
        montagemPanel.setMinimumSize(new java.awt.Dimension(800, 458));

        jPanel3.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout montagemPanelLayout = new javax.swing.GroupLayout(montagemPanel);
        montagemPanel.setLayout(montagemPanelLayout);
        montagemPanelLayout.setHorizontalGroup(
            montagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        montagemPanelLayout.setVerticalGroup(
            montagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(montagemPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 452, Short.MAX_VALUE))
        );

        montagemScrollPane.setViewportView(montagemPanel);

        contentPanel.add(montagemScrollPane, "montagemCard");

        homeScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        homeScrollPane.setBorder(null);
        homeScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        homeScrollPane.setMaximumSize(new java.awt.Dimension(800, 458));
        homeScrollPane.setMinimumSize(new java.awt.Dimension(800, 458));
        homeScrollPane.setPreferredSize(new java.awt.Dimension(800, 458));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setMaximumSize(new java.awt.Dimension(800, 32767));
        homePanel.setMinimumSize(new java.awt.Dimension(800, 458));
        homePanel.setPreferredSize(new java.awt.Dimension(800, 1000));

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        homeScrollPane.setViewportView(homePanel);

        contentPanel.add(homeScrollPane, "homeCard");

        loginScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        loginScrollPane.setBorder(null);
        loginScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        loginScrollPane.setMaximumSize(new java.awt.Dimension(800, 32767));
        loginScrollPane.setMinimumSize(new java.awt.Dimension(800, 458));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setMaximumSize(new java.awt.Dimension(800, 32767));
        loginPanel.setMinimumSize(new java.awt.Dimension(800, 458));

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButton1.setText("jButton1");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jButton1)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        loginScrollPane.setViewportView(loginPanel);

        contentPanel.add(loginScrollPane, "loginCard");

        mainPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void windowMinimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowMinimizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_windowMinimizeButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        this.cardLayout.show(contentPanel, "loginCard");
    }//GEN-LAST:event_userButtonActionPerformed

    private void windowCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowCloseButtonMouseClicked
       this.dispose();
    }//GEN-LAST:event_windowCloseButtonMouseClicked

    private void windowMinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowMinimizeButtonMouseClicked
        // TODO add your handling code here:
        Dimension minimumSize = this.minimumSize();
        
    }//GEN-LAST:event_windowMinimizeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarLabel;
    private javax.swing.JLabel carro;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton departamentosButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JScrollPane homeScrollPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JScrollPane loginScrollPane;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuBarPanel;
    private javax.swing.JPanel montagemPanel;
    private javax.swing.JScrollPane montagemScrollPane;
    private javax.swing.JPanel produtosPanel;
    private javax.swing.JScrollPane produtosScrollPane;
    private javax.swing.JButton userButton;
    private javax.swing.JPanel windowBarPanel;
    private javax.swing.JButton windowCloseButton;
    private javax.swing.JButton windowMinimizeButton;
    // End of variables declaration//GEN-END:variables
}
