package br.com.champtech.view;

import br.com.champtech.CustomIcon;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;

/*
 * @author denis_stiehler
 */
public final class MainFrame extends JFrame implements CustomIcon {

    public static MainFrame INSTANCE;

    private Object currentUser = null;
    
    private CardLayout tipoUsuarioLayout;
    private CardLayout clienteLayout;
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        // netbeans e suas implicâncias...................
        INSTANCE = this;

        initComponents();

        CustomIcon[] custonIcons = new CustomIcon[]{this, home, menuBar, produtos, departamentos};

        for (CustomIcon clazz : custonIcons) {
            clazz.loadIcons();
        }
        
        this.clienteLayout = (CardLayout) this.telas.getLayout();
        this.tipoUsuarioLayout = (CardLayout) this.tipoUsuario.getLayout();
        
        this.changeCurrentCard("clienteCard");
        this.changeCurrentCard("homeCard");
    }

    @Override
    public void loadIcons() {
        ImageIcon logoIcon = new ImageIcon("images/logo.png");
        
        ImageIcon icon = new ImageIcon("images/lupaPreta.png");
        //icon.setImage(icon.getImage().getScaledInstance(buscarButton.getWidth(), buscarButton.getHeight(), Image.SCALE_SMOOTH));
        //buscarButton.setIcon(icon);
        
        ImageIcon icon2 = new ImageIcon("images/addBtn.png");
        //icon2.setImage(icon2.getImage().getScaledInstance(buscarButton.getWidth(), buscarButton.getHeight(), Image.SCALE_SMOOTH));
        //buscarButton1.setIcon(icon2);
//        logoIcon.setImage(logoIcon.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH));
        //this.logo.setIcon(logoIcon);
    }

    // controlará TODAS as TROCAS de telas
    public void changeCurrentCard(String cardName) {

        System.out.println("[DEBUG] Trocando de tela para: " + cardName);

        switch (cardName) {
            case "clienteCard":
                tipoUsuarioLayout.show(tipoUsuario, cardName);
                break;
            case "funcionarioCard":
                tipoUsuarioLayout.show(tipoUsuario, cardName);
                break;
            default:
                CardLayout layout = (CardLayout) telas.getLayout();
                layout.show(telas, cardName);
                break;
        }

    }

    public boolean hasUser() {
        return Objects.nonNull(this.currentUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        windowTitileBar = new br.com.champtech.view.WindowTitileBar();
        tipoUsuario = new javax.swing.JPanel();
        cliente = new javax.swing.JPanel();
        departamentos = new br.com.champtech.view.cliente.Departamentos();
        menuBar = new br.com.champtech.view.cliente.MenuBar();
        telas = new javax.swing.JPanel();
        home = new br.com.champtech.view.cliente.Home();
        produtos = new br.com.champtech.view.cliente.Produtos();
        sacPanel = new br.com.champtech.view.cliente.SAC();
        montagem = new br.com.champtech.view.cliente.Montagem();
        loginPanel = new br.com.champtech.view.LoginPanel();
        funcionario = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChampTech");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout windowTitileBarLayout = new javax.swing.GroupLayout(windowTitileBar);
        windowTitileBar.setLayout(windowTitileBarLayout);
        windowTitileBarLayout.setHorizontalGroup(
            windowTitileBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        windowTitileBarLayout.setVerticalGroup(
            windowTitileBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        mainPanel.add(windowTitileBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tipoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tipoUsuario.setMaximumSize(new java.awt.Dimension(800, 578));
        tipoUsuario.setMinimumSize(new java.awt.Dimension(800, 578));
        tipoUsuario.setPreferredSize(new java.awt.Dimension(800, 578));
        tipoUsuario.setLayout(new java.awt.CardLayout());

        cliente.setBackground(new java.awt.Color(255, 255, 255));
        cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cliente.add(departamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        cliente.add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        telas.setBackground(new java.awt.Color(255, 255, 255));
        telas.setPreferredSize(new java.awt.Dimension(800, 498));
        telas.setLayout(new java.awt.CardLayout());
        telas.add(home, "homeCard");
        telas.add(produtos, "produtosCard");
        telas.add(sacPanel, "sacCard");
        telas.add(montagem, "montarCard");
        telas.add(loginPanel, "loginCard");

        cliente.add(telas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        tipoUsuario.add(cliente, "clienteCard");

        funcionario.setBackground(new java.awt.Color(255, 255, 255));
        funcionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 80));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        funcionario.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        funcionario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 810, 410));

        tipoUsuario.add(funcionario, "funcionarioCard");

        mainPanel.add(tipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cliente;
    public br.com.champtech.view.cliente.Departamentos departamentos;
    private javax.swing.JPanel funcionario;
    private br.com.champtech.view.cliente.Home home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private br.com.champtech.view.LoginPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private br.com.champtech.view.cliente.MenuBar menuBar;
    private br.com.champtech.view.cliente.Montagem montagem;
    private br.com.champtech.view.cliente.Produtos produtos;
    private br.com.champtech.view.cliente.SAC sacPanel;
    private javax.swing.JPanel telas;
    private javax.swing.JPanel tipoUsuario;
    private br.com.champtech.view.WindowTitileBar windowTitileBar;
    // End of variables declaration//GEN-END:variables
}
