package br.com.champtech.view.cliente;

import br.com.champtech.CustomIcon;
import br.com.champtech.view.MainFrame;
import javax.swing.ImageIcon;

/*
 * @author denis_stiehler
 */
public class Departamentos extends javax.swing.JPanel implements CustomIcon {

    private final MainFrame mainFrame;

    /*
     * Creates new form Departamentos
     */
    public Departamentos() {

        mainFrame = MainFrame.INSTANCE;

        initComponents();
        this.setVisible(false);
    }

    @Override
    public void loadIcons() {
        ImageIcon backgroundIocn = new ImageIcon("images/dropEsquerda.png");
        background.setIcon(backgroundIocn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(144, 160));
        setMinimumSize(new java.awt.Dimension(144, 160));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(144, 160));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Home");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 20, 90, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Montar PC");
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 60, 90, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Produtos");
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 100, 90, 40));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        background.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        background.setMaximumSize(new java.awt.Dimension(144, 160));
        background.setMinimumSize(new java.awt.Dimension(144, 160));
        background.setPreferredSize(new java.awt.Dimension(144, 160));
        background.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backgroundMouseExited(evt);
            }
        });
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 144, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseExited

        if (evt.getX() <= 0 || evt.getX() >= this.getWidth()) {
            this.setVisible(false);
        } else if (evt.getY() <= 0 || evt.getY() >= this.getHeight()) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_backgroundMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.mainFrame.changeCurrentCard("homeCard");
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.mainFrame.changeCurrentCard("montarCard");
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.mainFrame.changeCurrentCard("produtosCard");
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
