package br.com.champtech.view.cliente;

import br.com.champtech.CustomIcon;
import br.com.champtech.view.MainFrame;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * @author denis_stiehler
 */
public final class MenuBar extends JPanel implements CustomIcon {

    private static final String buscarMsg = "Buscar produtos...";

    // icones dos botões/labels.
    private static final String sacFileName = "images/sac.png";
    private static final String logoFileName = "images/logo.png";
    private static final String lupaFileName = "images/lupa.png";
    private static final String userFileName = "images/user.png";
    private static final String instaFileName = "images/insta.png";
    private static final String dropFileName = "images/dropdown.png";

    private final MainFrame mainFrame;

    /**
     * Creates new form MenuBar
     */
    public MenuBar() {

        this.mainFrame = MainFrame.INSTANCE;

        initComponents();
    }

    @Override
    public void loadIcons() {

        ImageIcon logo = new ImageIcon(logoFileName);
        logo.setImage(logo.getImage().getScaledInstance(logoButton.getWidth(), logoButton.getHeight(), Image.SCALE_SMOOTH));
        logoButton.setIcon(logo);

        ImageIcon lupa = new ImageIcon(lupaFileName);
        lupa.setImage(lupa.getImage().getScaledInstance(buscarButton.getWidth(), buscarButton.getHeight(), Image.SCALE_SMOOTH));
        buscarButton.setIcon(lupa);

        ImageIcon ateIcon = new ImageIcon(sacFileName);
        ateIcon.setImage(ateIcon.getImage().getScaledInstance(sacButton.getWidth(), sacButton.getHeight(), Image.SCALE_SMOOTH));
        sacButton.setIcon(ateIcon);

        ImageIcon user = new ImageIcon(userFileName);
        user.setImage(user.getImage().getScaledInstance(userButton.getWidth(), userButton.getHeight(), Image.SCALE_SMOOTH));
        userButton.setIcon(user);

        ImageIcon instaIcon = new ImageIcon(instaFileName);
        instaIcon.setImage(instaIcon.getImage().getScaledInstance(instaButton.getWidth(), instaButton.getHeight(), Image.SCALE_SMOOTH));
        instaButton.setIcon(instaIcon);

        ImageIcon dropdown = new ImageIcon(dropFileName);
        dropdown.setImage(dropdown.getImage().getScaledInstance(departamentosButton.getWidth(), departamentosButton.getHeight(), Image.SCALE_SMOOTH));
        departamentosButton.setIcon(dropdown);

        /*
        ImageIcon dropIcon = new ImageIcon("images/drop.png");
        //dropIcon.setImage(dropIcon.getImage().getScaledInstance(dropdownBg.getWidth(), dropdownBg.getHeight(), Image.SCALE_SMOOTH));
        dropdownBg.setIcon(dropIcon);

        ImageIcon dropIcon2 = new ImageIcon("images/dropDireita.png");
        //dropIcon.setImage(dropIcon.getImage().getScaledInstance(dropdownBg.getWidth(), dropdownBg.getHeight(), Image.SCALE_SMOOTH));
        dropdownBgUser.setIcon(dropIcon2);
        //dropdownBgUser dropDireita

        departamentoDropdown.setVisible(false);
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departamentosButton = new javax.swing.JButton();
        logoButton = new javax.swing.JButton();
        buscaInputField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        sacButton = new javax.swing.JButton();
        instaButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(800, 80));
        setMinimumSize(new java.awt.Dimension(800, 80));
        setPreferredSize(new java.awt.Dimension(800, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        departamentosButton.setBackground(new java.awt.Color(255, 255, 255));
        departamentosButton.setForeground(new java.awt.Color(255, 255, 255));
        departamentosButton.setBorderPainted(false);
        departamentosButton.setFocusPainted(false);
        departamentosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        departamentosButton.setOpaque(false);
        departamentosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                departamentosButtonMouseExited(evt);
            }
        });
        departamentosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentosButtonActionPerformed(evt);
            }
        });
        add(departamentosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, 30, 30));

        logoButton.setBorder(null);
        logoButton.setFocusPainted(false);
        logoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoButton.setMaximumSize(new java.awt.Dimension(200, 40));
        logoButton.setMinimumSize(new java.awt.Dimension(200, 40));
        logoButton.setOpaque(false);
        logoButton.setPreferredSize(new java.awt.Dimension(200, 40));
        logoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoButtonActionPerformed(evt);
            }
        });
        add(logoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        buscaInputField.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        buscaInputField.setForeground(new java.awt.Color(204, 204, 204));
        buscaInputField.setText("Buscar produtos...");
        buscaInputField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        buscaInputField.setCaretColor(new java.awt.Color(255, 255, 255));
        buscaInputField.setOpaque(false);
        buscaInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscaInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscaInputFieldFocusLost(evt);
            }
        });
        buscaInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaInputFieldActionPerformed(evt);
            }
        });
        add(buscaInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 26, 240, 30));

        buscarButton.setBorder(null);
        buscarButton.setContentAreaFilled(false);
        buscarButton.setFocusPainted(false);
        buscarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarButton.setPreferredSize(new java.awt.Dimension(30, 30));
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        sacButton.setBackground(new java.awt.Color(255, 255, 255));
        sacButton.setBorderPainted(false);
        sacButton.setContentAreaFilled(false);
        sacButton.setFocusPainted(false);
        sacButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sacButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacButtonActionPerformed(evt);
            }
        });
        add(sacButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 18, 35, 35));

        instaButton.setBackground(new java.awt.Color(255, 255, 255));
        instaButton.setBorderPainted(false);
        instaButton.setContentAreaFilled(false);
        instaButton.setFocusPainted(false);
        instaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        instaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instaButtonActionPerformed(evt);
            }
        });
        add(instaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 19, 35, 35));

        userButton.setBackground(new java.awt.Color(255, 255, 255));
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.setFocusPainted(false);
        userButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 17, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void buscaInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscaInputFieldFocusGained
        if (this.buscaInputField.getText().equals(buscarMsg)) {
            this.buscaInputField.setText("");
            this.buscaInputField.setForeground(Color.WHITE);
            this.buscaInputField.setFont(new Font("Tahoma", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_buscaInputFieldFocusGained

    private void buscaInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscaInputFieldFocusLost
        if (this.buscaInputField.getText().isBlank()) {
            this.buscaInputField.setText(buscarMsg);
            this.buscaInputField.setForeground(new Color(204, 204, 204));
            this.buscaInputField.setFont(new Font("Tahoma", Font.ITALIC, 14));
        }
    }//GEN-LAST:event_buscaInputFieldFocusLost

    private void logoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoButtonActionPerformed
        this.mainFrame.changeCurrentCard("homeCard");
    }//GEN-LAST:event_logoButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed

        if (this.mainFrame.hasUser()) {
            // abre dropdown do perfil
        } else {
            this.mainFrame.changeCurrentCard("loginCard");
        }
    }//GEN-LAST:event_userButtonActionPerformed

    private void instaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instaButtonActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("www.instagram.com/_champtech_"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_instaButtonActionPerformed

    private void sacButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacButtonActionPerformed
        this.mainFrame.changeCurrentCard("sacCard");
    }//GEN-LAST:event_sacButtonActionPerformed

    private void departamentosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentosButtonActionPerformed
        // abre ou fecha o dropdown de departamentos
        this.mainFrame.departamentos.setVisible(!this.mainFrame.departamentos.isVisible());
        // ...
    }//GEN-LAST:event_departamentosButtonActionPerformed

    private void buscaInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaInputFieldActionPerformed
        if (!buscaInputField.getText().isBlank() && !buscaInputField.getText().equals(buscarMsg)) {
            this.mainFrame.changeCurrentCard("produtosCard");
        }
    }//GEN-LAST:event_buscaInputFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        if (!buscaInputField.getText().isBlank() && !buscaInputField.getText().equals(buscarMsg)) {
            this.mainFrame.changeCurrentCard("produtosCard");
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void departamentosButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentosButtonMouseExited
        if (evt.getX() <= 0 || evt.getX() >= this.departamentosButton.getWidth()) {
            this.mainFrame.departamentos.setVisible(false);
        } else if (evt.getY() <= 0) {
            this.mainFrame.departamentos.setVisible(false);
        }
    }//GEN-LAST:event_departamentosButtonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscaInputField;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton departamentosButton;
    private javax.swing.JButton instaButton;
    private javax.swing.JButton logoButton;
    private javax.swing.JButton sacButton;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
