package br.com.champtech.view.cliente;

import br.com.champtech.CustomIcon;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/*
 * @author denis_stiehler
 */
public class Produtos extends JPanel implements CustomIcon {

    /*
     * Creates new form Produtos
     */
    public Produtos() {
        initComponents();

        // alinha os itens do comboBox ao centro.
        ((JLabel) categoriaCombo.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

        loadingLbl.setVisible(false);
    }

    @Override
    public void loadIcons() {

        ImageIcon loadingIcon = new ImageIcon("images/loading.gif");
        loadingLbl.setIcon(loadingIcon);

        ImageIcon filtroIcon = new ImageIcon("images/filtro.png");
        filtroIcon.setImage(filtroIcon.getImage().getScaledInstance(filtroIconLbl.getWidth(), filtroIconLbl.getHeight(), Image.SCALE_SMOOTH));
        filtroIconLbl.setIcon(filtroIcon);

        // CARREGAMENTO ESTÁTICO DOS PRODUTOS, FUTURAMENTE CARREGARÁ DO BANCO
        ImageIcon prod1 = new ImageIcon("images/r7.png");
        prod1.setImage(prod1.getImage().getScaledInstance(imgProdLbl1.getWidth(), imgProdLbl1.getHeight(), Image.SCALE_SMOOTH));
        imgProdLbl1.setIcon(prod1);
        imgProdLbl2.setIcon(prod1);
        imgProdLbl3.setIcon(prod1);
        imgProdLbl4.setIcon(prod1);
        imgProdLbl5.setIcon(prod1);
        imgProdLbl6.setIcon(prod1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precoButtonGroup = new javax.swing.ButtonGroup();
        filtrosPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filtroIconLbl = new javax.swing.JLabel();
        filtroLbl = new javax.swing.JLabel();
        aplicarBtn = new javax.swing.JButton();
        categoriaLbl = new javax.swing.JLabel();
        categoriaCombo = new javax.swing.JComboBox<>();
        ordemLbl = new javax.swing.JLabel();
        maiorRadBtn = new javax.swing.JRadioButton();
        menorRadBtn = new javax.swing.JRadioButton();
        tipo = new javax.swing.JPanel();
        gabinete = new javax.swing.JPanel();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        Memória2 = new javax.swing.JLabel();
        ram = new javax.swing.JPanel();
        frequeLbl = new javax.swing.JLabel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        processador = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        placaMae = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        fonte = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox28 = new javax.swing.JCheckBox();
        video = new javax.swing.JPanel();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        Memória = new javax.swing.JLabel();
        jCheckBox26 = new javax.swing.JCheckBox();
        armazenamento = new javax.swing.JPanel();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        Memória1 = new javax.swing.JLabel();
        nada = new javax.swing.JPanel();
        produtosPanel = new javax.swing.JPanel();
        loadingLbl = new javax.swing.JLabel();
        antPagBtn = new javax.swing.JButton();
        nextPagBtn = new javax.swing.JButton();
        produtoPanel2 = new javax.swing.JPanel();
        imgProdLbl2 = new javax.swing.JLabel();
        catProdLbl2 = new javax.swing.JLabel();
        nomeProdLbl2 = new javax.swing.JLabel();
        precoLbl2 = new javax.swing.JLabel();
        produtoPanel1 = new javax.swing.JPanel();
        imgProdLbl1 = new javax.swing.JLabel();
        catProdLbl1 = new javax.swing.JLabel();
        nomeProdLbl1 = new javax.swing.JLabel();
        precoLbl1 = new javax.swing.JLabel();
        produtoPanel3 = new javax.swing.JPanel();
        imgProdLbl3 = new javax.swing.JLabel();
        catProdLbl3 = new javax.swing.JLabel();
        nomeProdLbl3 = new javax.swing.JLabel();
        precoLbl3 = new javax.swing.JLabel();
        produtoPanel4 = new javax.swing.JPanel();
        imgProdLbl4 = new javax.swing.JLabel();
        catProdLbl4 = new javax.swing.JLabel();
        nomeProdLbl4 = new javax.swing.JLabel();
        precoLbl4 = new javax.swing.JLabel();
        produtoPanel5 = new javax.swing.JPanel();
        imgProdLbl5 = new javax.swing.JLabel();
        catProdLbl5 = new javax.swing.JLabel();
        nomeProdLbl5 = new javax.swing.JLabel();
        precoLbl5 = new javax.swing.JLabel();
        produtoPanel6 = new javax.swing.JPanel();
        imgProdLbl6 = new javax.swing.JLabel();
        catProdLbl6 = new javax.swing.JLabel();
        nomeProdLbl6 = new javax.swing.JLabel();
        precoLbl6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 498));
        setMinimumSize(new java.awt.Dimension(800, 498));
        setPreferredSize(new java.awt.Dimension(800, 498));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filtrosPanel.setBackground(new java.awt.Color(102, 102, 102));
        filtrosPanel.setMaximumSize(new java.awt.Dimension(170, 498));
        filtrosPanel.setMinimumSize(new java.awt.Dimension(170, 498));
        filtrosPanel.setPreferredSize(new java.awt.Dimension(170, 498));
        filtrosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Departamentos > Processador");
        filtrosPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        filtroIconLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filtroIconLbl.setPreferredSize(new java.awt.Dimension(20, 20));
        filtrosPanel.add(filtroIconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        filtroLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        filtroLbl.setForeground(new java.awt.Color(255, 255, 255));
        filtroLbl.setText("Filtros");
        filtrosPanel.add(filtroLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, 70, 40));

        aplicarBtn.setBackground(new java.awt.Color(255, 153, 0));
        aplicarBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aplicarBtn.setForeground(new java.awt.Color(255, 255, 255));
        aplicarBtn.setText("Aplicar");
        aplicarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        aplicarBtn.setBorderPainted(false);
        aplicarBtn.setFocusPainted(false);
        filtrosPanel.add(aplicarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 44, 60, 20));

        categoriaLbl.setBackground(new java.awt.Color(0, 204, 153));
        categoriaLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categoriaLbl.setForeground(new java.awt.Color(255, 255, 255));
        categoriaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoriaLbl.setText("Categoria");
        categoriaLbl.setToolTipText("");
        categoriaLbl.setOpaque(true);
        filtrosPanel.add(categoriaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 30));

        categoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa-Mãe", "Processador", "Placa de Vídeo", "Memória Ram", "Fonte", "Armazenamento", "Gabinete", "Cooler", "Computador" }));
        categoriaCombo.setBorder(null);
        categoriaCombo.setFocusable(false);
        categoriaCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoriaComboItemStateChanged(evt);
            }
        });
        categoriaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaComboActionPerformed(evt);
            }
        });
        filtrosPanel.add(categoriaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 20));

        ordemLbl.setBackground(new java.awt.Color(0, 204, 153));
        ordemLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ordemLbl.setForeground(new java.awt.Color(255, 255, 255));
        ordemLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordemLbl.setText("Ordenar por:");
        ordemLbl.setToolTipText("");
        ordemLbl.setOpaque(true);
        filtrosPanel.add(ordemLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 30));

        precoButtonGroup.add(maiorRadBtn);
        maiorRadBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maiorRadBtn.setForeground(new java.awt.Color(255, 255, 255));
        maiorRadBtn.setSelected(true);
        maiorRadBtn.setText("Maior Preco");
        maiorRadBtn.setFocusPainted(false);
        maiorRadBtn.setOpaque(false);
        filtrosPanel.add(maiorRadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));

        precoButtonGroup.add(menorRadBtn);
        menorRadBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        menorRadBtn.setForeground(new java.awt.Color(255, 255, 255));
        menorRadBtn.setText("Menor Preco");
        menorRadBtn.setFocusPainted(false);
        menorRadBtn.setOpaque(false);
        filtrosPanel.add(menorRadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 176, -1, -1));

        tipo.setOpaque(false);
        tipo.setPreferredSize(new java.awt.Dimension(200, 296));
        tipo.setLayout(new java.awt.CardLayout());

        gabinete.setBackground(new java.awt.Color(102, 102, 102));
        gabinete.setOpaque(false);

        jCheckBox34.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox34.setText("M-ATX");
        jCheckBox34.setFocusPainted(false);
        jCheckBox34.setOpaque(false);

        jCheckBox36.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox36.setText("F-ATX");
        jCheckBox36.setFocusPainted(false);
        jCheckBox36.setOpaque(false);

        jCheckBox37.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox37.setText("ATX");
        jCheckBox37.setFocusPainted(false);
        jCheckBox37.setOpaque(false);

        jCheckBox38.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox38.setText("E-ATX");
        jCheckBox38.setFocusPainted(false);
        jCheckBox38.setOpaque(false);

        Memória2.setBackground(new java.awt.Color(0, 204, 153));
        Memória2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Memória2.setForeground(new java.awt.Color(255, 255, 255));
        Memória2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Memória2.setText("Formato");
        Memória2.setToolTipText("");
        Memória2.setOpaque(true);

        javax.swing.GroupLayout gabineteLayout = new javax.swing.GroupLayout(gabinete);
        gabinete.setLayout(gabineteLayout);
        gabineteLayout.setHorizontalGroup(
            gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gabineteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Memória2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gabineteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox34)
                            .addComponent(jCheckBox37))
                        .addGap(18, 18, 18)
                        .addGroup(gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox38)
                            .addComponent(jCheckBox36)))))
        );
        gabineteLayout.setVerticalGroup(
            gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gabineteLayout.createSequentialGroup()
                .addComponent(Memória2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox34)
                    .addComponent(jCheckBox36))
                .addGap(8, 8, 8)
                .addGroup(gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox37)
                    .addComponent(jCheckBox38))
                .addGap(0, 196, Short.MAX_VALUE))
        );

        tipo.add(gabinete, "gabineteCard");

        ram.setBackground(new java.awt.Color(102, 102, 102));
        ram.setOpaque(false);

        frequeLbl.setBackground(new java.awt.Color(0, 204, 153));
        frequeLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        frequeLbl.setForeground(new java.awt.Color(255, 255, 255));
        frequeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frequeLbl.setText("Frequência");
        frequeLbl.setToolTipText("");
        frequeLbl.setOpaque(true);

        jCheckBox21.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox21.setText("2666 MHz");
        jCheckBox21.setFocusPainted(false);
        jCheckBox21.setOpaque(false);

        jCheckBox22.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox22.setText("2400 MHz");
        jCheckBox22.setFocusPainted(false);
        jCheckBox22.setOpaque(false);

        jCheckBox23.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox23.setText("2133 MHz");
        jCheckBox23.setFocusPainted(false);
        jCheckBox23.setOpaque(false);

        jCheckBox24.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox24.setText("3000 MHz");
        jCheckBox24.setFocusPainted(false);
        jCheckBox24.setOpaque(false);

        jCheckBox25.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox25.setText("3200 MHz");
        jCheckBox25.setFocusPainted(false);
        jCheckBox25.setOpaque(false);

        javax.swing.GroupLayout ramLayout = new javax.swing.GroupLayout(ram);
        ram.setLayout(ramLayout);
        ramLayout.setHorizontalGroup(
            ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ramLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frequeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ramLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ramLayout.createSequentialGroup()
                                .addComponent(jCheckBox23)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox24))
                            .addGroup(ramLayout.createSequentialGroup()
                                .addComponent(jCheckBox22)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox25))
                            .addComponent(jCheckBox21)))))
        );
        ramLayout.setVerticalGroup(
            ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ramLayout.createSequentialGroup()
                .addComponent(frequeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox23)
                    .addComponent(jCheckBox24))
                .addGap(8, 8, 8)
                .addGroup(ramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox22)
                    .addComponent(jCheckBox25))
                .addGap(8, 8, 8)
                .addComponent(jCheckBox21)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        tipo.add(ram, "ramCard");

        processador.setBackground(new java.awt.Color(102, 102, 102));
        processador.setOpaque(false);

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Intel Core i7");
        jCheckBox1.setFocusPainted(false);
        jCheckBox1.setOpaque(false);

        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Intel Core i5");
        jCheckBox3.setFocusPainted(false);
        jCheckBox3.setOpaque(false);

        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Intel Core i3");
        jCheckBox4.setFocusPainted(false);
        jCheckBox4.setOpaque(false);

        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("AMD Ryzen");
        jCheckBox5.setFocusPainted(false);
        jCheckBox5.setOpaque(false);

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("AMD FX");
        jCheckBox2.setFocusPainted(false);
        jCheckBox2.setOpaque(false);

        jLabel7.setBackground(new java.awt.Color(0, 204, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Séries");
        jLabel7.setToolTipText("");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout processadorLayout = new javax.swing.GroupLayout(processador);
        processador.setLayout(processadorLayout);
        processadorLayout.setHorizontalGroup(
            processadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processadorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(processadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(processadorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(processadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(processadorLayout.createSequentialGroup()
                                .addComponent(jCheckBox4)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox5))
                            .addGroup(processadorLayout.createSequentialGroup()
                                .addComponent(jCheckBox3)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox2))
                            .addComponent(jCheckBox1)))))
        );
        processadorLayout.setVerticalGroup(
            processadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processadorLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(processadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5))
                .addGap(8, 8, 8)
                .addGroup(processadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2))
                .addGap(8, 8, 8)
                .addComponent(jCheckBox1)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        tipo.add(processador, "processadorCard");

        placaMae.setBackground(new java.awt.Color(102, 102, 102));
        placaMae.setOpaque(false);

        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("LGA 1150");
        jCheckBox6.setFocusPainted(false);
        jCheckBox6.setOpaque(false);

        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("LGA 1151");
        jCheckBox7.setFocusPainted(false);
        jCheckBox7.setOpaque(false);

        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("LGA 1155");
        jCheckBox8.setFocusPainted(false);
        jCheckBox8.setOpaque(false);

        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("AM4");
        jCheckBox9.setFocusPainted(false);
        jCheckBox9.setOpaque(false);

        jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setText("AM3+");
        jCheckBox10.setFocusPainted(false);
        jCheckBox10.setOpaque(false);

        jLabel8.setBackground(new java.awt.Color(0, 204, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Socket");
        jLabel8.setToolTipText("");
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout placaMaeLayout = new javax.swing.GroupLayout(placaMae);
        placaMae.setLayout(placaMaeLayout);
        placaMaeLayout.setHorizontalGroup(
            placaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, placaMaeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(placaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(placaMaeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(placaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(placaMaeLayout.createSequentialGroup()
                                .addComponent(jCheckBox8)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox9))
                            .addGroup(placaMaeLayout.createSequentialGroup()
                                .addComponent(jCheckBox7)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox10))
                            .addComponent(jCheckBox6)))))
        );
        placaMaeLayout.setVerticalGroup(
            placaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placaMaeLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(placaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9))
                .addGap(8, 8, 8)
                .addGroup(placaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox10))
                .addGap(8, 8, 8)
                .addComponent(jCheckBox6)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        tipo.add(placaMae, "maeCard");

        fonte.setBackground(new java.awt.Color(102, 102, 102));
        fonte.setOpaque(false);

        jCheckBox11.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setText("600 - 650 W");
        jCheckBox11.setFocusPainted(false);
        jCheckBox11.setOpaque(false);

        jCheckBox12.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setText("500 - 550 W");
        jCheckBox12.setFocusPainted(false);
        jCheckBox12.setOpaque(false);

        jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setText("400 - 450 W");
        jCheckBox13.setFocusPainted(false);
        jCheckBox13.setOpaque(false);

        jCheckBox14.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox14.setText("700 - 750 W");
        jCheckBox14.setFocusPainted(false);
        jCheckBox14.setOpaque(false);

        jCheckBox15.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox15.setText("800 - 850 W");
        jCheckBox15.setFocusPainted(false);
        jCheckBox15.setOpaque(false);

        jLabel9.setBackground(new java.awt.Color(0, 204, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Potência");
        jLabel9.setToolTipText("");
        jLabel9.setOpaque(true);

        jCheckBox28.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox28.setText("900 W +");
        jCheckBox28.setFocusPainted(false);
        jCheckBox28.setOpaque(false);

        javax.swing.GroupLayout fonteLayout = new javax.swing.GroupLayout(fonte);
        fonte.setLayout(fonteLayout);
        fonteLayout.setHorizontalGroup(
            fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fonteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fonteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fonteLayout.createSequentialGroup()
                                .addComponent(jCheckBox13)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox14))
                            .addGroup(fonteLayout.createSequentialGroup()
                                .addGroup(fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox12)
                                    .addComponent(jCheckBox11))
                                .addGap(4, 4, 4)
                                .addGroup(fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox28)
                                    .addComponent(jCheckBox15)))))))
        );
        fonteLayout.setVerticalGroup(
            fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fonteLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox14))
                .addGap(8, 8, 8)
                .addGroup(fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox15))
                .addGap(8, 8, 8)
                .addGroup(fonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox28))
                .addGap(0, 166, Short.MAX_VALUE))
        );

        tipo.add(fonte, "fonteCard");

        video.setBackground(new java.awt.Color(102, 102, 102));
        video.setOpaque(false);

        jCheckBox18.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox18.setText("2 GB");
        jCheckBox18.setFocusPainted(false);
        jCheckBox18.setOpaque(false);

        jCheckBox20.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox20.setText("8 GB");
        jCheckBox20.setFocusPainted(false);
        jCheckBox20.setOpaque(false);

        jCheckBox16.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox16.setText("4 gb");
        jCheckBox16.setFocusPainted(false);
        jCheckBox16.setOpaque(false);

        jCheckBox17.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox17.setText("3 GB");
        jCheckBox17.setFocusPainted(false);
        jCheckBox17.setOpaque(false);

        jCheckBox19.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox19.setText("6 GB");
        jCheckBox19.setFocusPainted(false);
        jCheckBox19.setOpaque(false);

        Memória.setBackground(new java.awt.Color(0, 204, 153));
        Memória.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Memória.setForeground(new java.awt.Color(255, 255, 255));
        Memória.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Memória.setText("Memória");
        Memória.setToolTipText("");
        Memória.setOpaque(true);

        jCheckBox26.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox26.setText("11 GB");
        jCheckBox26.setFocusPainted(false);
        jCheckBox26.setOpaque(false);

        javax.swing.GroupLayout videoLayout = new javax.swing.GroupLayout(video);
        video.setLayout(videoLayout);
        videoLayout.setHorizontalGroup(
            videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, videoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Memória, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(videoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(videoLayout.createSequentialGroup()
                                .addComponent(jCheckBox18)
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox19))
                            .addGroup(videoLayout.createSequentialGroup()
                                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox17)
                                    .addComponent(jCheckBox16))
                                .addGap(4, 4, 4)
                                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox26)
                                    .addComponent(jCheckBox20)))))))
        );
        videoLayout.setVerticalGroup(
            videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoLayout.createSequentialGroup()
                .addComponent(Memória, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox19))
                .addGap(8, 8, 8)
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox20))
                .addGap(8, 8, 8)
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox26))
                .addGap(0, 166, Short.MAX_VALUE))
        );

        tipo.add(video, "videoCard");

        armazenamento.setBackground(new java.awt.Color(102, 102, 102));
        armazenamento.setOpaque(false);

        jCheckBox27.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox27.setText("HD");
        jCheckBox27.setFocusPainted(false);
        jCheckBox27.setOpaque(false);

        jCheckBox31.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox31.setText("SSD");
        jCheckBox31.setFocusPainted(false);
        jCheckBox31.setOpaque(false);

        Memória1.setBackground(new java.awt.Color(0, 204, 153));
        Memória1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Memória1.setForeground(new java.awt.Color(255, 255, 255));
        Memória1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Memória1.setText("Tipo");
        Memória1.setToolTipText("");
        Memória1.setOpaque(true);

        javax.swing.GroupLayout armazenamentoLayout = new javax.swing.GroupLayout(armazenamento);
        armazenamento.setLayout(armazenamentoLayout);
        armazenamentoLayout.setHorizontalGroup(
            armazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, armazenamentoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(armazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Memória1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(armazenamentoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBox27)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox31))))
        );
        armazenamentoLayout.setVerticalGroup(
            armazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armazenamentoLayout.createSequentialGroup()
                .addComponent(Memória1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(armazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox27)
                    .addComponent(jCheckBox31))
                .addGap(0, 226, Short.MAX_VALUE))
        );

        tipo.add(armazenamento, "armazenamentoCard");

        nada.setBackground(new java.awt.Color(102, 102, 102));
        nada.setOpaque(false);

        javax.swing.GroupLayout nadaLayout = new javax.swing.GroupLayout(nada);
        nada.setLayout(nadaLayout);
        nadaLayout.setHorizontalGroup(
            nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        nadaLayout.setVerticalGroup(
            nadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        tipo.add(nada, "nadaCard");

        filtrosPanel.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 202, -1, -1));

        add(filtrosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        produtosPanel.setBackground(new java.awt.Color(255, 255, 255));
        produtosPanel.setPreferredSize(new java.awt.Dimension(600, 498));
        produtosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        produtosPanel.add(loadingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 360, 340));

        antPagBtn.setBackground(new java.awt.Color(204, 204, 204));
        antPagBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        antPagBtn.setForeground(new java.awt.Color(255, 255, 255));
        antPagBtn.setText("<");
        antPagBtn.setToolTipText("Não há mais páginas");
        antPagBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 153), 1, true));
        antPagBtn.setBorderPainted(false);
        antPagBtn.setFocusPainted(false);
        antPagBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        antPagBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        antPagBtn.setPreferredSize(new java.awt.Dimension(22, 22));
        produtosPanel.add(antPagBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 235, -1, -1));

        nextPagBtn.setBackground(new java.awt.Color(0, 204, 153));
        nextPagBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nextPagBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextPagBtn.setText(">");
        nextPagBtn.setToolTipText("Próxima página");
        nextPagBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 153), 1, true));
        nextPagBtn.setBorderPainted(false);
        nextPagBtn.setFocusPainted(false);
        nextPagBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nextPagBtn.setPreferredSize(new java.awt.Dimension(22, 22));
        produtosPanel.add(nextPagBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 235, -1, -1));

        produtoPanel2.setBackground(new java.awt.Color(255, 255, 255));
        produtoPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        produtoPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produtoPanel2.add(imgProdLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        catProdLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catProdLbl2.setText("Placa de Vídeo");
        produtoPanel2.add(catProdLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        nomeProdLbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeProdLbl2.setForeground(new java.awt.Color(255, 153, 0));
        nomeProdLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeProdLbl2.setText("Ryzen 5 3600");
        produtoPanel2.add(nomeProdLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        precoLbl2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        precoLbl2.setForeground(new java.awt.Color(0, 204, 0));
        precoLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoLbl2.setText("R$ 900,00");
        precoLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        produtoPanel2.add(precoLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 20));

        produtosPanel.add(produtoPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 25, 150, 220));

        produtoPanel1.setBackground(new java.awt.Color(255, 255, 255));
        produtoPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        produtoPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produtoPanel1.add(imgProdLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        catProdLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catProdLbl1.setText("Placa de Vídeo");
        produtoPanel1.add(catProdLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        nomeProdLbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeProdLbl1.setForeground(new java.awt.Color(255, 153, 0));
        nomeProdLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeProdLbl1.setText("Ryzen 5 3600");
        produtoPanel1.add(nomeProdLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        precoLbl1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        precoLbl1.setForeground(new java.awt.Color(0, 204, 0));
        precoLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoLbl1.setText("R$ 900,00");
        precoLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        produtoPanel1.add(precoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 20));

        produtosPanel.add(produtoPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, 220));

        produtoPanel3.setBackground(new java.awt.Color(255, 255, 255));
        produtoPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        produtoPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produtoPanel3.add(imgProdLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        catProdLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catProdLbl3.setText("Placa de Vídeo");
        produtoPanel3.add(catProdLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        nomeProdLbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeProdLbl3.setForeground(new java.awt.Color(255, 153, 0));
        nomeProdLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeProdLbl3.setText("Ryzen 5 3600");
        produtoPanel3.add(nomeProdLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        precoLbl3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        precoLbl3.setForeground(new java.awt.Color(0, 204, 0));
        precoLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoLbl3.setText("R$ 900,00");
        precoLbl3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        produtoPanel3.add(precoLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 20));

        produtosPanel.add(produtoPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 150, 220));

        produtoPanel4.setBackground(new java.awt.Color(255, 255, 255));
        produtoPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        produtoPanel4.setMaximumSize(new java.awt.Dimension(150, 200));
        produtoPanel4.setMinimumSize(new java.awt.Dimension(150, 200));
        produtoPanel4.setPreferredSize(new java.awt.Dimension(150, 200));
        produtoPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produtoPanel4.add(imgProdLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        catProdLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catProdLbl4.setText("Placa de Vídeo");
        produtoPanel4.add(catProdLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        nomeProdLbl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeProdLbl4.setForeground(new java.awt.Color(255, 153, 0));
        nomeProdLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeProdLbl4.setText("Ryzen 5 3600");
        produtoPanel4.add(nomeProdLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        precoLbl4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        precoLbl4.setForeground(new java.awt.Color(0, 204, 0));
        precoLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoLbl4.setText("R$ 99.900,00");
        precoLbl4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        precoLbl4.setMaximumSize(new java.awt.Dimension(150, 25));
        precoLbl4.setMinimumSize(new java.awt.Dimension(150, 25));
        precoLbl4.setPreferredSize(new java.awt.Dimension(150, 200));
        produtoPanel4.add(precoLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 20));

        produtosPanel.add(produtoPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 25, 150, 220));

        produtoPanel5.setBackground(new java.awt.Color(255, 255, 255));
        produtoPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        produtoPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produtoPanel5.add(imgProdLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        catProdLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catProdLbl5.setText("Placa de Vídeo");
        produtoPanel5.add(catProdLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        nomeProdLbl5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeProdLbl5.setForeground(new java.awt.Color(255, 153, 0));
        nomeProdLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeProdLbl5.setText("Ryzen 5 3600");
        produtoPanel5.add(nomeProdLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        precoLbl5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        precoLbl5.setForeground(new java.awt.Color(0, 204, 0));
        precoLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoLbl5.setText("R$ 900,00");
        precoLbl5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        produtoPanel5.add(precoLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 20));

        produtosPanel.add(produtoPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 220));

        produtoPanel6.setBackground(new java.awt.Color(255, 255, 255));
        produtoPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        produtoPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produtoPanel6.add(imgProdLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        catProdLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catProdLbl6.setText("Placa de Vídeo");
        produtoPanel6.add(catProdLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        nomeProdLbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeProdLbl6.setForeground(new java.awt.Color(255, 153, 0));
        nomeProdLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeProdLbl6.setText("Ryzen 5 3600");
        produtoPanel6.add(nomeProdLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        precoLbl6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        precoLbl6.setForeground(new java.awt.Color(0, 204, 0));
        precoLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precoLbl6.setText("R$ 900,00");
        precoLbl6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        produtoPanel6.add(precoLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 20));

        produtosPanel.add(produtoPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 150, 220));

        add(produtosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoriaComboItemStateChanged

    }//GEN-LAST:event_categoriaComboItemStateChanged

    private void categoriaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaComboActionPerformed

        CardLayout layout = (CardLayout) tipo.getLayout();

        // que horror, refataorar para usar enum......................
        switch (((String) categoriaCombo.getSelectedItem()).trim()) {
            case "Processador":
                layout.show(tipo, "processadorCard");
                break;
            case "Placa-Mãe":
                layout.show(tipo, "maeCard");
                break;
            case "Fonte":
                layout.show(tipo, "fonteCard");
                break;
            case "Placa de Vídeo":
                layout.show(tipo, "videoCard");
                break;
            case "Memória Ram":
                layout.show(tipo, "ramCard");
                break;
            case "Gabinete":
                layout.show(tipo, "gabineteCard");
                break;
            case "Armazenamento":
                layout.show(tipo, "armazenamentoCard");
                break;
            case "Cooler":
                // filtra pelo suporte ao socket do processador por isso usa o mesmo card
                layout.show(tipo, "maeCard");
                break;
            case "Computador":
                // nao há
                layout.show(tipo, "nadaCard");
                break;

        }
    }//GEN-LAST:event_categoriaComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Memória;
    private javax.swing.JLabel Memória1;
    private javax.swing.JLabel Memória2;
    private javax.swing.JButton antPagBtn;
    private javax.swing.JButton aplicarBtn;
    private javax.swing.JPanel armazenamento;
    private javax.swing.JLabel catProdLbl1;
    private javax.swing.JLabel catProdLbl2;
    private javax.swing.JLabel catProdLbl3;
    private javax.swing.JLabel catProdLbl4;
    private javax.swing.JLabel catProdLbl5;
    private javax.swing.JLabel catProdLbl6;
    private javax.swing.JComboBox<String> categoriaCombo;
    private javax.swing.JLabel categoriaLbl;
    private javax.swing.JLabel filtroIconLbl;
    private javax.swing.JLabel filtroLbl;
    private javax.swing.JPanel filtrosPanel;
    private javax.swing.JPanel fonte;
    private javax.swing.JLabel frequeLbl;
    private javax.swing.JPanel gabinete;
    public static javax.swing.JLabel imgProdLbl1;
    public static javax.swing.JLabel imgProdLbl2;
    public static javax.swing.JLabel imgProdLbl3;
    public static javax.swing.JLabel imgProdLbl4;
    public static javax.swing.JLabel imgProdLbl5;
    public static javax.swing.JLabel imgProdLbl6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel loadingLbl;
    private javax.swing.JRadioButton maiorRadBtn;
    private javax.swing.JRadioButton menorRadBtn;
    private javax.swing.JPanel nada;
    private javax.swing.JButton nextPagBtn;
    private javax.swing.JLabel nomeProdLbl1;
    private javax.swing.JLabel nomeProdLbl2;
    private javax.swing.JLabel nomeProdLbl3;
    private javax.swing.JLabel nomeProdLbl4;
    private javax.swing.JLabel nomeProdLbl5;
    private javax.swing.JLabel nomeProdLbl6;
    private javax.swing.JLabel ordemLbl;
    private javax.swing.JPanel placaMae;
    private javax.swing.ButtonGroup precoButtonGroup;
    private javax.swing.JLabel precoLbl1;
    private javax.swing.JLabel precoLbl2;
    private javax.swing.JLabel precoLbl3;
    private javax.swing.JLabel precoLbl4;
    private javax.swing.JLabel precoLbl5;
    private javax.swing.JLabel precoLbl6;
    private javax.swing.JPanel processador;
    public static javax.swing.JPanel produtoPanel1;
    public static javax.swing.JPanel produtoPanel2;
    public static javax.swing.JPanel produtoPanel3;
    public static javax.swing.JPanel produtoPanel4;
    public static javax.swing.JPanel produtoPanel5;
    public static javax.swing.JPanel produtoPanel6;
    private javax.swing.JPanel produtosPanel;
    private javax.swing.JPanel ram;
    private javax.swing.JPanel tipo;
    private javax.swing.JPanel video;
    // End of variables declaration//GEN-END:variables
}
